/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.programacion.ejb;

/**
 * Home interface for ProgramacionFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface ProgramacionFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ProgramacionFacadeEJB";
   public static final String JNDI_NAME="ejb/facade/rrhh/programacion/AsisProgramacionFacadeEJB";

   public pe.gob.sunat.rrhh.programacion.ejb.ProgramacionFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
