/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.asistencia.ejb;

/**
 * Home interface for AutorizaLaborFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface AutorizaLaborFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AutorizaLaborFacadeEJB";
   public static final String JNDI_NAME="ejb/facade/rrhh/asistencia/AutorizaLaborFacadeEJB";

   public pe.gob.sunat.rrhh.asistencia.ejb.AutorizaLaborFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
