/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.asistencia.ejb;

/**
 * Home interface for AutomatizarAsistenciaFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface AutomatizarAsistenciaFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AutomatizarAsistenciaFacadeEJB";
   public static final String JNDI_NAME="ejb/facade/rrhh/asistencia/AutomatizarAsistenciaFacadeEJB";

   public pe.gob.sunat.rrhh.asistencia.ejb.AutomatizarAsistenciaFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
