/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.asistencia.ejb;

/**
 * Remote interface for AutomatizarAsistenciaFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface AutomatizarAsistenciaFacadeRemote
   extends javax.ejb.EJBObject
{
   /**
    * Encargado de generar registro de asistencia en forma automatico
    * @throws DAOException
    * @throws RemoteException    */
   public void mainSchedulerAsistencia(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Encargado de generar registro de asistencia en forma automatico
    * @throws DAOException
    * @throws RemoteException    */
   public void generarRegistroAsistencia(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * encargado de procesar la asistencia de forma automatica
    * @throws DAOException
    * @throws RemoteException    */
   public void procesarAsistencia(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * encargado de procesar novedad de la labor excepcional de forma automatica
    * @throws DAOException
    * @throws RemoteException    */
   public void novedad_procesarLaborExcepcional(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * encargado de procesar la labor excepcional de forma automatica
    * @throws DAOException
    * @throws RemoteException    */
   public void procesarLaborExcepcional(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Encargado de generar registro de asistencia en forma automatico
    * @throws DAOException
    * @throws RemoteException    */
   public void generarSaldosVacacionales(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * encargado de calcular y enviar alertas por acumulacion de inasistencias
    * @throws DAOException
    * @throws RemoteException    */
   public void enviarAlertaInasistencias(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Encargado de generar registro de asistencia en forma automatico
    * @throws DAOException
    * @throws RemoteException    */
   public void novedad_generarRegistroAsistencia(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * encargado de procesar la asistencia de forma automatica
    * @throws DAOException
    * @throws RemoteException    */
   public void novedad_procesarAsistencia(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * MÃƒÂ©todo encargado de enviar alertas de vacaciones a trabajadores en forma automÃƒÂ¡tica
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarAlertaVacaciones(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * Metodo que envia correo con archivo zipeado resumen de notificaciones de vacaciones enviadas en una fecha
    * @param dcsp DataSource
    * @param mapaDatos Map
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarCorreo_NotificacionesVacacionesEnviadas( javax.sql.DataSource dcsp,java.util.Map mapaDatos )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * Encargado de calcular y enviar alertas de solicitudes a jefes y directivos
    * @throws DAOException
    * @throws RemoteException    */
   public void enviarAlertaSolicitudes(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * MÃƒÂ©todo encargado de enviar alertas de solicitudes vacacionales pendientes en forma automÃƒÂ¡tica
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarAlertaSolicitudVacacionesPendientes(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * MÃƒÂ©todo encargado de enviar alertas de solicitudes vacacionales pendientes en forma automÃƒÂ¡tica
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarAlertaPersonalSinTurno(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Encargado de calcular y enviar alertas de movimientos de asistencia a trabajadores
    * @throws DAOException
    * @throws RemoteException    */
   public void enviarAlertaMovAsistencia(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Genera una cadena que contiene una tabla html con los datos del Trabajador Solicitante
    * @param dbean DynaBean
    * @param hm HashMap
    * @return 
    * @throws FacadeException    */
   public java.lang.String generaTablaDatos( java.util.List lista,java.lang.String strURL )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Genera una cadena que contiene una tabla html con los datos de los movimientos de asistencia de trabajadores
    * @param dbean DynaBean
    * @param hm HashMap
    * @return 
    * @throws FacadeException    */
   public java.lang.String generaTablaDatosMovAsis( java.util.List lista,java.lang.String strURL )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Metodo encargado de enviar alertas de cambio de turno a trabajadores en forma automatica
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarAlertaCambioTurno(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * Encargado de procesar clima laboral en un rango de fechas en forma automatico
    * @throws FacadeException
    * @throws DAOException
    * @throws RemoteException    */
   public void procesarClimaLaboral(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * Metodo encargado de enviar automaticamente alertas a directivos con relacion adjunta de colaboradores con programacion de vacaciones
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarAlertaConProgramacionVacaciones(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * Metodo que envia correos con archivo zipeado excel de resumen de notificaciones enviadas a directivos en una fecha
    * @param dgsp DataSource
    * @param mapaDatos Map
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarCorreosRRHH_ResumenNotificacionesConProgramacion( javax.sql.DataSource dcsp,java.util.Map mapaDatos )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * Metodo encargado de enviar automaticamente alertas a directivos con relacion adjunta de colaboradores sin programacion de vacaciones para periodo vigente respecto a una fecha de corte
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarAlertaSinProgramacionVacaciones(  )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * Metodo que envia correos con archivo zipeado excel de resumen de notificaciones enviadas a directivos (sin programacion vacaciones) en una fecha
    * @param dgsp DataSource
    * @param mapaDatos Map
    * @param listaRRHH List
    * @throws FacadeException
    * @throws RemoteException
    * @throws CreateException    */
   public void enviarCorreosRRHH_ResumenNotificacionesSinProgramacion( javax.sql.DataSource dcsp,java.util.Map mapaDatos,java.util.List listaRRHH )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, javax.ejb.CreateException, java.rmi.RemoteException;

   /**
    * Metodo encargado de obtener el codigo de unidad organica restando los ceros empezando desde el final hasta el caracter que no sea cero
    * @param String unidad
    * @return String uoJefe
    * @throws FacadeException    */
   public java.lang.String findUuooJefe( java.lang.String unidad )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Metodo que devuelve el texto en html para la alerta a directivos con programacion de trabajadores
    * @param params Map
    * @return String
    * @throws FacadeException    */
   public java.lang.String textoCorreoAlertaDirectivoConProgramaciones( java.util.Map params )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Metodo que devuelve el texto en html para la alerta a directivos sin programacion de trabajadores
    * @param params Map
    * @return String
    * @throws FacadeException    */
   public java.lang.String textoCorreoAlertaDirectivoSinProgramaciones( java.util.Map params )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * metodo retornaSaldo: que se encarga de retornar el saldo de un anio vacacional para una persona
    * @param List listaSaldos
    * @return String, retorna el saldo
    * @throws FacadeException
    */
   public java.lang.String retornaSaldo( java.util.List listaSaldos,java.lang.String codPersona,java.lang.String annovac )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Genera una cadena que contiene una tabla html con turnos para alerta de cambio de turno
    * @param lista List
    * @return String
    * @throws FacadeException    */
   public java.lang.String generaTablaAlertaCambioTurno( java.util.List lista )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Metodo que devuelve el texto en html para la alerta de cambio de turno
    * @param params Map
    * @param nombre String
    * @param mensaje String
    * @return String
    * @throws FacadeException    */
   public java.lang.String textoCorreoAlertaCambioTurno( java.util.Map params,java.lang.String nombre,java.lang.String mensaje )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   /**
    * Metodo que devuelve el texto en html para el envio de correo de procesamiento por clima laboral
    * @param params Map
    * @param nombre String
    * @param mensaje String
    * @return String
    * @throws FacadeException    */
   public java.lang.String textoCorreoClimaLaboral( java.util.Map params,java.lang.String nombre,java.lang.String mensaje )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

}
