/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.formativa.ejb;

/**
 * Remote interface for AsisForMasivoFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface AsisForMasivoFacadeRemote
   extends javax.ejb.EJBObject
{
   /**
    * Obtiene las MArcaciones Masivas de los Formativas
    * @param params HashMap
    * @param usuario String
    * @return 
    * @throws RemoteException    */
   public void marcaciones( java.util.HashMap params,java.lang.String usuario )
      throws java.rmi.RemoteException;

}
