/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.formativa.ejb;

/**
 * Home interface for AsisForFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface AsisForFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AsisForFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/rrhh/formativa/AsisForFacadeAsistencia";

   public pe.gob.sunat.rrhh.formativa.ejb.AsisForFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
