/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.formativa.ejb;

/**
 * Remote interface for AsisForFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface AsisForFacadeRemote
   extends javax.ejb.EJBObject
{

   public java.util.ArrayList marcaciones( java.util.Map datos )
      throws pe.gob.sunat.framework.core.ejb.FacadeException, java.rmi.RemoteException;

   public void masivoMarcaciones( java.util.Map params )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

}
