/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.formativa.ejb;

/**
 * Home interface for AsisForMasivoFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface AsisForMasivoFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AsisForMasivoFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/rrhh/formativa/AsisForMasivoFacadeEJB";

   public pe.gob.sunat.rrhh.formativa.ejb.AsisForMasivoFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
