/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.rrhh.padron.ejb;

/**
 * Home interface for PadronFacade.
 * @xdoclet-generado el 03-02-2020
 */
public interface PadronFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PadronFacade";
   public static final String JNDI_NAME="ejb/facade/rrhh/padron/PadronFacadeAsistencia";

   public pe.gob.sunat.rrhh.padron.ejb.PadronFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
