/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Remote interface for ArchivoFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface ArchivoFacadeRemote
   extends javax.ejb.EJBObject
{
   /**
    * Obtener archivo
    * @param dbPool
    * @param mapa: Mapa con campos num_archivo , num_arcdet
    * @return Mapa con nombre e inputStream con archivo
    * @throws IncompleteConversationalState
    * @throws RemoteException
    */
   public java.util.Map descargarArchivo( java.lang.String dbPool,java.util.Map mapa )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   /**
    * Buscar archivos no borrados
    * @param dbpool
    * @param mapa: Mapa con campos num_archivo , num_seqdoc
    * @return lista de archivos
    */
   public java.util.List buscarArchivos( java.lang.String dbpool,java.util.Map mapa )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   /**
    * Guarda los archivos temporales a permanentes
    * @param dbpool : conexion
    * @param mapa : mapa con num_archivo
    * @return Numero de archivos insertados
    * @throws IncompleteConversationalState
    * @throws RemoteException
    */
   public int registrarEnPermanente( java.lang.String dbpool,java.util.Map mapa )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   /**
    * Insertar Cabecera
    * @param dbpool : conexion
    * @param mapa : mapa con num_archivo
    * @return Numero de archivos insertados
    * @throws IncompleteConversationalState
    * @throws RemoteException
    */
   public int insertarArchivoCabecera( java.lang.String dbpool,java.util.Map mapa )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   /**
    * Insertar Detalle de archivo
    * @param dbpool : conexion
    * @param mapa : mapa con num_archivo
    * @return Numero de archivos insertados
    * @throws IncompleteConversationalState
    * @throws RemoteException
    */
   public int insertarArchivoDetalle( java.lang.String dbpool,java.util.Map mapa )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   /**
    * Obtener siguiente numero en la secuencia para archivos
    * @return siguiente numero de archivo
    */
   public int obtenerNumArchivo(  )
      throws java.rmi.RemoteException;

}
