/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for ArchivoTmpFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface ArchivoTmpFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ArchivoTmpFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/ArchivoTmpFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.ArchivoTmpFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
