/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for AsistenciaFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface AsistenciaFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AsistenciaFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/AsistenciaFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.AsistenciaFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
