/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for HoraExtraFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface HoraExtraFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HoraExtraFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/HoraExtraFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.HoraExtraFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
