/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for LicenciaFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface LicenciaFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LicenciaFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/LicenciaFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.LicenciaFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
