/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for ProcesoFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface ProcesoFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ProcesoFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/ProcesoFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.ProcesoFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
