/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for ReporteMasivoFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface ReporteMasivoFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ReporteMasivoFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/ReporteMasivoFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.ReporteMasivoFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
