/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for ReporteFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface ReporteFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ReporteFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/ReporteFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.ReporteFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
