/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for SolicitudFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface SolicitudFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SolicitudFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/SolicitudFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.SolicitudFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
