/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T1278CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T1278CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String periodo;
   public java.lang.String uOrgan;

   public T1278CMPPK()
   {
   }

   public T1278CMPPK( java.lang.String periodo,java.lang.String UOrgan )
   {
      this.periodo = periodo;
      this.uOrgan = UOrgan;
   }

   public java.lang.String getPeriodo()
   {
      return periodo;
   }
   public java.lang.String getUOrgan()
   {
      return uOrgan;
   }

   public void setPeriodo(java.lang.String periodo)
   {
      this.periodo = periodo;
   }
   public void setUOrgan(java.lang.String uOrgan)
   {
      this.uOrgan = uOrgan;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.periodo != null) _hashCode += this.periodo.hashCode();
         if (this.uOrgan != null) _hashCode += this.uOrgan.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T1278CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T1278CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T1278CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.periodo != null )
         {
            eq = eq && this.periodo.equals( pk.getPeriodo() );
         }
         else  // this.periodo == null
         {
            eq = eq && ( pk.getPeriodo() == null );
         }
         if( this.uOrgan != null )
         {
            eq = eq && this.uOrgan.equals( pk.getUOrgan() );
         }
         else  // this.uOrgan == null
         {
            eq = eq && ( pk.getUOrgan() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.periodo).append('.');
         toStringValue.append(this.uOrgan).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
