/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T1275CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T1275CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String codPers;
   public java.sql.Date fecha;
   public java.lang.String hora;
   public java.lang.String reloj;

   public T1275CMPPK()
   {
   }

   public T1275CMPPK( java.lang.String codPers,java.sql.Date fecha,java.lang.String hora,java.lang.String reloj )
   {
      this.codPers = codPers;
      this.fecha = fecha;
      this.hora = hora;
      this.reloj = reloj;
   }

   public java.lang.String getCodPers()
   {
      return codPers;
   }
   public java.sql.Date getFecha()
   {
      return fecha;
   }
   public java.lang.String getHora()
   {
      return hora;
   }
   public java.lang.String getReloj()
   {
      return reloj;
   }

   public void setCodPers(java.lang.String codPers)
   {
      this.codPers = codPers;
   }
   public void setFecha(java.sql.Date fecha)
   {
      this.fecha = fecha;
   }
   public void setHora(java.lang.String hora)
   {
      this.hora = hora;
   }
   public void setReloj(java.lang.String reloj)
   {
      this.reloj = reloj;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.codPers != null) _hashCode += this.codPers.hashCode();
         if (this.fecha != null) _hashCode += this.fecha.hashCode();
         if (this.hora != null) _hashCode += this.hora.hashCode();
         if (this.reloj != null) _hashCode += this.reloj.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T1275CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T1275CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T1275CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.codPers != null )
         {
            eq = eq && this.codPers.equals( pk.getCodPers() );
         }
         else  // this.codPers == null
         {
            eq = eq && ( pk.getCodPers() == null );
         }
         if( this.fecha != null )
         {
            eq = eq && this.fecha.equals( pk.getFecha() );
         }
         else  // this.fecha == null
         {
            eq = eq && ( pk.getFecha() == null );
         }
         if( this.hora != null )
         {
            eq = eq && this.hora.equals( pk.getHora() );
         }
         else  // this.hora == null
         {
            eq = eq && ( pk.getHora() == null );
         }
         if( this.reloj != null )
         {
            eq = eq && this.reloj.equals( pk.getReloj() );
         }
         else  // this.reloj == null
         {
            eq = eq && ( pk.getReloj() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.codPers).append('.');
         toStringValue.append(this.fecha).append('.');
         toStringValue.append(this.hora).append('.');
         toStringValue.append(this.reloj).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
