/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T1279CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1279CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setMov( java.lang.String mov ) ;

   public void setDescrip( java.lang.String descrip ) ;

   public void setCalifica( java.lang.String califica ) ;

   public void setMedida( java.lang.String medida ) ;

   public void setEstId( java.lang.String estId ) ;

   public void setTipoId( java.lang.String tipoId ) ;

   public void setFini( java.sql.Timestamp fini ) ;

   public void setFfin( java.sql.Timestamp ffin ) ;

   public void setSoliId( java.lang.String soliId ) ;

   public void setRrhhId( java.lang.String rrhhId ) ;

   public void setProcId( java.lang.String procId ) ;

   public void setEntrId( java.lang.String entrId ) ;

   public void setRefrId( java.lang.String refrId ) ;

   public void setSaliId( java.lang.String saliId ) ;

   public void setDiasAntes( java.lang.Integer diasAntes ) ;

   public void setDiasDespues( java.lang.Integer diasDespues ) ;

   public void setDiasAcum( java.lang.Integer diasAcum ) ;

   public void setObligId( java.lang.String obligId ) ;

   public void setFgraba( java.sql.Timestamp fgraba ) ;

   public void setCuser( java.lang.String cuser ) ;

   public void setQValida( int qvalida ) ;

   public void setIndDias( java.lang.String ind_dias ) ;

   public void setIndProc( java.lang.String ind_proc ) ;

   public java.lang.String getMov(  ) ;

   public java.lang.String getDescrip(  ) ;

   public java.lang.String getCalifica(  ) ;

   public java.lang.String getMedida(  ) ;

   public java.lang.String getEstId(  ) ;

   public java.lang.String getTipoId(  ) ;

   public java.sql.Timestamp getFini(  ) ;

   public java.sql.Timestamp getFfin(  ) ;

   public java.lang.String getSoliId(  ) ;

   public java.lang.String getRrhhId(  ) ;

   public java.lang.String getProcId(  ) ;

   public java.lang.String getEntrId(  ) ;

   public java.lang.String getRefrId(  ) ;

   public java.lang.String getSaliId(  ) ;

   public java.lang.Integer getDiasAntes(  ) ;

   public java.lang.Integer getDiasDespues(  ) ;

   public java.lang.Integer getDiasAcum(  ) ;

   public java.lang.String getObligId(  ) ;

   public java.sql.Timestamp getFgraba(  ) ;

   public java.lang.String getCuser(  ) ;

   public int getQValida(  ) ;

   public java.lang.String getIndDias(  ) ;

   public java.lang.String getIndProc(  ) ;

}
