/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T1279CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T1279CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String mov;

   public T1279CMPPK()
   {
   }

   public T1279CMPPK( java.lang.String mov )
   {
      this.mov = mov;
   }

   public java.lang.String getMov()
   {
      return mov;
   }

   public void setMov(java.lang.String mov)
   {
      this.mov = mov;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.mov != null) _hashCode += this.mov.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T1279CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T1279CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T1279CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.mov != null )
         {
            eq = eq && this.mov.equals( pk.getMov() );
         }
         else  // this.mov == null
         {
            eq = eq && ( pk.getMov() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.mov).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
