/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T1278CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1278CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setPeriodo( java.lang.String periodo ) ;

   public void setUOrgan( java.lang.String uOrgan ) ;

   public void setEstId( java.lang.String estId ) ;

   public void setFgraba( java.sql.Timestamp fgraba ) ;

   public void setCuser( java.lang.String cuser ) ;

   public java.lang.String getPeriodo(  ) ;

   public java.lang.String getUOrgan(  ) ;

   public java.lang.String getEstId(  ) ;

   public java.sql.Timestamp getFgraba(  ) ;

   public java.lang.String getCuser(  ) ;

}
