/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local home interface for T1275CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1275CMPHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/T1275CMPLocal";
   public static final String JNDI_NAME="ejb/rrhh/cmp/sp/asistencia/t1275cmp";

   public pe.gob.sunat.sp.asistencia.ejb.T1275CMPLocal create(java.lang.String codPers , java.sql.Date fecha , java.lang.String hora , java.lang.String reloj)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1275CMPLocal findByPrimaryKey(pe.gob.sunat.sp.asistencia.ejb.T1275CMPPK pk)
      throws javax.ejb.FinderException;

}
