/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local home interface for T1279CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1279CMPHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/T1279CMPLocal";
   public static final String JNDI_NAME="ejb/rrhh/cmp/sp/asistencia/t1279cmp";

   public pe.gob.sunat.sp.asistencia.ejb.T1279CMPLocal create(java.lang.String codMovimiento , java.lang.String descripcion , java.lang.String califica , java.lang.String medida , java.lang.String estId , java.lang.String tipo , java.sql.Timestamp fechaIni , java.sql.Timestamp fechaFin , java.lang.String soliId , java.lang.String vbRrHh , java.lang.String procId , java.lang.String entrId , java.lang.String refrId , java.lang.String saliId , java.lang.Integer diasAntes , java.lang.Integer diasDespues , java.lang.Integer diasAcum , java.lang.String obligId , java.sql.Timestamp fgraba , java.lang.String cuser , java.lang.String ind_dias)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1279CMPLocal findByPrimaryKey(pe.gob.sunat.sp.asistencia.ejb.T1279CMPPK pk)
      throws javax.ejb.FinderException;

}
