/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local home interface for T1278CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1278CMPHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/T1278CMPLocal";
   public static final String JNDI_NAME="ejb/rrhh/cmp/sp/asistencia/t1278cmp";

   public pe.gob.sunat.sp.asistencia.ejb.T1278CMPLocal create(java.lang.String periodo , java.lang.String uOrgan)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1278CMPLocal create(java.lang.String periodo , java.lang.String uOrgan , java.lang.String estId , java.sql.Timestamp fgraba , java.lang.String usuario)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1278CMPLocal findByPrimaryKey(pe.gob.sunat.sp.asistencia.ejb.T1278CMPPK pk)
      throws javax.ejb.FinderException;

}
