/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T1281CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1281CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setCodPers( java.lang.String codPers ) ;

   public void setAnno( java.lang.String anno ) ;

   public void setDias( java.lang.Integer dias ) ;

   public void setSaldo( java.lang.Integer saldo ) ;

   public void setSaldoTemp( java.lang.Integer saldoTemp ) ;

   public void setFcreacion( java.sql.Timestamp fcreacion ) ;

   public void setFmod( java.sql.Timestamp fmod ) ;

   public void setCuserMod( java.lang.String cuserMod ) ;

   public void setCuserCrea( java.lang.String cuserCrea ) ;

   public java.lang.String getCodPers(  ) ;

   public java.lang.String getAnno(  ) ;

   public java.lang.Integer getDias(  ) ;

   public java.lang.Integer getSaldo(  ) ;

   public java.lang.Integer getSaldoTemp(  ) ;

   public java.sql.Timestamp getFcreacion(  ) ;

   public java.sql.Timestamp getFmod(  ) ;

   public java.lang.String getCuserMod(  ) ;

   public java.lang.String getCuserCrea(  ) ;

}
