/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T1280CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T1280CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String reloj;

   public T1280CMPPK()
   {
   }

   public T1280CMPPK( java.lang.String reloj )
   {
      this.reloj = reloj;
   }

   public java.lang.String getReloj()
   {
      return reloj;
   }

   public void setReloj(java.lang.String reloj)
   {
      this.reloj = reloj;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.reloj != null) _hashCode += this.reloj.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T1280CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T1280CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T1280CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.reloj != null )
         {
            eq = eq && this.reloj.equals( pk.getReloj() );
         }
         else  // this.reloj == null
         {
            eq = eq && ( pk.getReloj() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.reloj).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
