/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T1281CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T1281CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String codPers;
   public java.lang.String anno;

   public T1281CMPPK()
   {
   }

   public T1281CMPPK( java.lang.String codPers,java.lang.String anno )
   {
      this.codPers = codPers;
      this.anno = anno;
   }

   public java.lang.String getCodPers()
   {
      return codPers;
   }
   public java.lang.String getAnno()
   {
      return anno;
   }

   public void setCodPers(java.lang.String codPers)
   {
      this.codPers = codPers;
   }
   public void setAnno(java.lang.String anno)
   {
      this.anno = anno;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.codPers != null) _hashCode += this.codPers.hashCode();
         if (this.anno != null) _hashCode += this.anno.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T1281CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T1281CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T1281CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.codPers != null )
         {
            eq = eq && this.codPers.equals( pk.getCodPers() );
         }
         else  // this.codPers == null
         {
            eq = eq && ( pk.getCodPers() == null );
         }
         if( this.anno != null )
         {
            eq = eq && this.anno.equals( pk.getAnno() );
         }
         else  // this.anno == null
         {
            eq = eq && ( pk.getAnno() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.codPers).append('.');
         toStringValue.append(this.anno).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
