/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local home interface for T1280CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1280CMPHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/T1280CMPLocal";
   public static final String JNDI_NAME="ejb/rrhh/cmp/sp/asistencia/t1280cmp";

   public pe.gob.sunat.sp.asistencia.ejb.T1280CMPLocal create(java.lang.String reloj)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1280CMPLocal create(java.lang.String reloj , java.lang.String descrip , java.lang.String sede , java.lang.String estId , java.sql.Timestamp fgraba , java.lang.String cuser)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1280CMPLocal findByPrimaryKey(pe.gob.sunat.sp.asistencia.ejb.T1280CMPPK pk)
      throws javax.ejb.FinderException;

}
