/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T1280CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1280CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setReloj( java.lang.String reloj ) ;

   public void setDescrip( java.lang.String descrip ) ;

   public void setSede( java.lang.String sede ) ;

   public void setEstId( java.lang.String estId ) ;

   public void setFgraba( java.sql.Timestamp fgraba ) ;

   public void setCuser( java.lang.String cuser ) ;

   public java.lang.String getReloj(  ) ;

   public java.lang.String getDescrip(  ) ;

   public java.lang.String getSede(  ) ;

   public java.lang.String getEstId(  ) ;

   public java.sql.Timestamp getFgraba(  ) ;

   public java.lang.String getCuser(  ) ;

}
