/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T130CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T130CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setCodPers( java.lang.String codPers ) ;

   public void setFAutor( java.lang.String fAutor ) ;

   public void setHInic( java.lang.String hInic ) ;

   public void setCodUrga( java.lang.String codUrga ) ;

   public void setHTerm( java.lang.String hTerm ) ;

   public void setObserva( java.lang.String observa ) ;

   public void setCodJefe( java.lang.String codJefe ) ;

   public void setFEfect( java.lang.String fEfect ) ;

   public void setHSalid( java.lang.String hSalid ) ;

   public void setIdConfir( java.lang.Short idConfir ) ;

   public void setEstId( java.lang.String estId ) ;

   public void setFcreacion( java.sql.Timestamp fcreacion ) ;

   public void setCodUser( java.lang.String codUser ) ;

   public void setFmod( java.sql.Timestamp fmod ) ;

   public void setCuserMod( java.lang.String cuserMod ) ;

   public java.lang.String getCodPers(  ) ;

   public java.lang.String getFAutor(  ) ;

   public java.lang.String getHInic(  ) ;

   public java.lang.String getCodUrga(  ) ;

   public java.lang.String getHTerm(  ) ;

   public java.lang.String getObserva(  ) ;

   public java.lang.String getCodJefe(  ) ;

   public java.lang.String getFEfect(  ) ;

   public java.lang.String getHSalid(  ) ;

   public java.lang.Short getIdConfir(  ) ;

   public java.lang.String getEstId(  ) ;

   public java.sql.Timestamp getFcreacion(  ) ;

   public java.lang.String getCodUser(  ) ;

   public java.sql.Timestamp getFmod(  ) ;

   public java.lang.String getCuserMod(  ) ;

}
