/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local home interface for T132CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T132CMPHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/T132CMPLocal";
   public static final String JNDI_NAME="ejb/rrhh/cmp/sp/asistencia/t132cmp";

   public pe.gob.sunat.sp.asistencia.ejb.T132CMPLocal create(java.lang.String codPers)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T132CMPLocal create(java.lang.String codPers , java.math.BigDecimal total , java.lang.String estado , java.sql.Timestamp fecha , java.lang.String usuario)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T132CMPLocal findByPrimaryKey(pe.gob.sunat.sp.asistencia.ejb.T132CMPPK pk)
      throws javax.ejb.FinderException;

}
