/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T132CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T132CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String codPers;

   public T132CMPPK()
   {
   }

   public T132CMPPK( java.lang.String codPers )
   {
      this.codPers = codPers;
   }

   public java.lang.String getCodPers()
   {
      return codPers;
   }

   public void setCodPers(java.lang.String codPers)
   {
      this.codPers = codPers;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.codPers != null) _hashCode += this.codPers.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T132CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T132CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T132CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.codPers != null )
         {
            eq = eq && this.codPers.equals( pk.getCodPers() );
         }
         else  // this.codPers == null
         {
            eq = eq && ( pk.getCodPers() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.codPers).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
