/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T1444CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T1444CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String codPers;
   public java.lang.String periodo;
   public java.lang.String mov;

   public T1444CMPPK()
   {
   }

   public T1444CMPPK( java.lang.String codPers,java.lang.String periodo,java.lang.String mov )
   {
      this.codPers = codPers;
      this.periodo = periodo;
      this.mov = mov;
   }

   public java.lang.String getCodPers()
   {
      return codPers;
   }
   public java.lang.String getPeriodo()
   {
      return periodo;
   }
   public java.lang.String getMov()
   {
      return mov;
   }

   public void setCodPers(java.lang.String codPers)
   {
      this.codPers = codPers;
   }
   public void setPeriodo(java.lang.String periodo)
   {
      this.periodo = periodo;
   }
   public void setMov(java.lang.String mov)
   {
      this.mov = mov;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.codPers != null) _hashCode += this.codPers.hashCode();
         if (this.periodo != null) _hashCode += this.periodo.hashCode();
         if (this.mov != null) _hashCode += this.mov.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T1444CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T1444CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T1444CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.codPers != null )
         {
            eq = eq && this.codPers.equals( pk.getCodPers() );
         }
         else  // this.codPers == null
         {
            eq = eq && ( pk.getCodPers() == null );
         }
         if( this.periodo != null )
         {
            eq = eq && this.periodo.equals( pk.getPeriodo() );
         }
         else  // this.periodo == null
         {
            eq = eq && ( pk.getPeriodo() == null );
         }
         if( this.mov != null )
         {
            eq = eq && this.mov.equals( pk.getMov() );
         }
         else  // this.mov == null
         {
            eq = eq && ( pk.getMov() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.codPers).append('.');
         toStringValue.append(this.periodo).append('.');
         toStringValue.append(this.mov).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
