/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T1444CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1444CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setCodPers( java.lang.String codPers ) ;

   public void setPeriodo( java.lang.String periodo ) ;

   public void setMov( java.lang.String mov ) ;

   public void setTotal( java.lang.Integer total ) ;

   public void setPeriodReg( java.lang.String periodReg ) ;

   public void setObserv( java.lang.String observ ) ;

   public void setFcreacion( java.sql.Timestamp fcreacion ) ;

   public void setCuserCrea( java.lang.String cuserCrea ) ;

   public void setFmod( java.sql.Timestamp fmod ) ;

   public void setCuserMod( java.lang.String cuserMod ) ;

   public java.lang.String getCodPers(  ) ;

   public java.lang.String getPeriodo(  ) ;

   public java.lang.String getMov(  ) ;

   public java.lang.Integer getTotal(  ) ;

   public java.lang.String getPeriodReg(  ) ;

   public java.lang.String getObserv(  ) ;

   public java.sql.Timestamp getFcreacion(  ) ;

   public java.lang.String getCuserCrea(  ) ;

   public java.sql.Timestamp getFmod(  ) ;

   public java.lang.String getCuserMod(  ) ;

}
