/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local home interface for T1444CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1444CMPHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/T1444CMPLocal";
   public static final String JNDI_NAME="ejb/rrhh/cmp/sp/asistencia/t1444cmp";

   public pe.gob.sunat.sp.asistencia.ejb.T1444CMPLocal create(java.lang.String codPers , java.lang.String periodo , java.lang.String mov)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1444CMPLocal create(java.lang.String codPers , java.lang.String periodo , java.lang.String mov , java.lang.Integer total , java.lang.String periodoReg , java.lang.String observacion , java.sql.Timestamp fCreacion , java.lang.String usuario)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1444CMPLocal findByPrimaryKey(pe.gob.sunat.sp.asistencia.ejb.T1444CMPPK pk)
      throws javax.ejb.FinderException;

}
