/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T1456CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1456CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setCodPers( java.lang.String codPers ) ;

   public void setFecha( java.sql.Date fecha ) ;

   public void setEstId( java.lang.String estId ) ;

   public void setFcreacion( java.sql.Timestamp fcreacion ) ;

   public void setCuserCrea( java.lang.String cuserCrea ) ;

   public void setFmod( java.sql.Timestamp fmod ) ;

   public void setCuserMod( java.lang.String cuserMod ) ;

   public java.lang.String getCodPers(  ) ;

   public java.sql.Date getFecha(  ) ;

   public java.lang.String getEstId(  ) ;

   public java.sql.Timestamp getFcreacion(  ) ;

   public java.lang.String getCuserCrea(  ) ;

   public java.sql.Timestamp getFmod(  ) ;

   public java.lang.String getCuserMod(  ) ;

}
