/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T1456CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T1456CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String codPers;
   public java.sql.Date fecha;

   public T1456CMPPK()
   {
   }

   public T1456CMPPK( java.lang.String codPers,java.sql.Date fecha )
   {
      this.codPers = codPers;
      this.fecha = fecha;
   }

   public java.lang.String getCodPers()
   {
      return codPers;
   }
   public java.sql.Date getFecha()
   {
      return fecha;
   }

   public void setCodPers(java.lang.String codPers)
   {
      this.codPers = codPers;
   }
   public void setFecha(java.sql.Date fecha)
   {
      this.fecha = fecha;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.codPers != null) _hashCode += this.codPers.hashCode();
         if (this.fecha != null) _hashCode += this.fecha.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T1456CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T1456CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T1456CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.codPers != null )
         {
            eq = eq && this.codPers.equals( pk.getCodPers() );
         }
         else  // this.codPers == null
         {
            eq = eq && ( pk.getCodPers() == null );
         }
         if( this.fecha != null )
         {
            eq = eq && this.fecha.equals( pk.getFecha() );
         }
         else  // this.fecha == null
         {
            eq = eq && ( pk.getFecha() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.codPers).append('.');
         toStringValue.append(this.fecha).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
