/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T1480CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1480CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setUOrgan( java.lang.String uorgan ) ;

   public void setCodPersOri( java.lang.String cod_pers_ori ) ;

   public void setCodPersDes( java.lang.String cod_pers_des ) ;

   public void setAccion( java.lang.String accion ) ;

   public void setInstancia( java.lang.String instancia ) ;

   public void setMov( java.lang.String mov ) ;

   public void setFGraba( java.sql.Timestamp fgraba ) ;

   public void setCUser( java.lang.String cuser ) ;

   public java.lang.String getUOrgan(  ) ;

   public java.lang.String getCodPersOri(  ) ;

   public java.lang.String getCodPersDes(  ) ;

   public java.lang.String getAccion(  ) ;

   public java.lang.String getMov(  ) ;

   public java.lang.String getInstancia(  ) ;

   public java.sql.Timestamp getFGraba(  ) ;

   public java.lang.String getCUser(  ) ;

}
