/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local home interface for T1480CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1480CMPHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/T1480CMPLocal";
   public static final String JNDI_NAME="ejb/rrhh/cmp/sp/asistencia/t1480cmp";

   public pe.gob.sunat.sp.asistencia.ejb.T1480CMPLocal create(java.util.Map data)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1480CMPLocal findByPrimaryKey(pe.gob.sunat.sp.asistencia.ejb.T1480CMPPK pk)
      throws javax.ejb.FinderException;

}
