/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local home interface for T1485CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1485CMPHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/T1485CMPLocal";
   public static final String JNDI_NAME="ejb/rrhh/cmp/sp/asistencia/t1485cmp";

   public pe.gob.sunat.sp.asistencia.ejb.T1485CMPLocal create(java.util.Map data)
      throws javax.ejb.CreateException;

   public pe.gob.sunat.sp.asistencia.ejb.T1485CMPLocal findByPrimaryKey(pe.gob.sunat.sp.asistencia.ejb.T1485CMPPK pk)
      throws javax.ejb.FinderException;

}
