/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Primary key for T1480CMP.
 * @xdoclet-generated at 03-02-2020
 */
public class T1480CMPPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String uOrgan;
   public java.lang.String codPersOri;
   public java.lang.String accion;
   public java.lang.String mov;

   public T1480CMPPK()
   {
   }

   public T1480CMPPK( java.lang.String UOrgan,java.lang.String codPersOri,java.lang.String accion,java.lang.String mov )
   {
      this.uOrgan = UOrgan;
      this.codPersOri = codPersOri;
      this.accion = accion;
      this.mov = mov;
   }

   public java.lang.String getUOrgan()
   {
      return uOrgan;
   }
   public java.lang.String getCodPersOri()
   {
      return codPersOri;
   }
   public java.lang.String getAccion()
   {
      return accion;
   }
   public java.lang.String getMov()
   {
      return mov;
   }

   public void setUOrgan(java.lang.String uOrgan)
   {
      this.uOrgan = uOrgan;
   }
   public void setCodPersOri(java.lang.String codPersOri)
   {
      this.codPersOri = codPersOri;
   }
   public void setAccion(java.lang.String accion)
   {
      this.accion = accion;
   }
   public void setMov(java.lang.String mov)
   {
      this.mov = mov;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.uOrgan != null) _hashCode += this.uOrgan.hashCode();
         if (this.codPersOri != null) _hashCode += this.codPersOri.hashCode();
         if (this.accion != null) _hashCode += this.accion.hashCode();
         if (this.mov != null) _hashCode += this.mov.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof pe.gob.sunat.sp.asistencia.ejb.T1480CMPPK) )
         return false;

      pe.gob.sunat.sp.asistencia.ejb.T1480CMPPK pk = (pe.gob.sunat.sp.asistencia.ejb.T1480CMPPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.uOrgan != null )
         {
            eq = eq && this.uOrgan.equals( pk.getUOrgan() );
         }
         else  // this.uOrgan == null
         {
            eq = eq && ( pk.getUOrgan() == null );
         }
         if( this.codPersOri != null )
         {
            eq = eq && this.codPersOri.equals( pk.getCodPersOri() );
         }
         else  // this.codPersOri == null
         {
            eq = eq && ( pk.getCodPersOri() == null );
         }
         if( this.accion != null )
         {
            eq = eq && this.accion.equals( pk.getAccion() );
         }
         else  // this.accion == null
         {
            eq = eq && ( pk.getAccion() == null );
         }
         if( this.mov != null )
         {
            eq = eq && this.mov.equals( pk.getMov() );
         }
         else  // this.mov == null
         {
            eq = eq && ( pk.getMov() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.uOrgan).append('.');
         toStringValue.append(this.codPersOri).append('.');
         toStringValue.append(this.accion).append('.');
         toStringValue.append(this.mov).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
