/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T1485CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T1485CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setUOrgan( java.lang.String uorgan ) ;

   public void setCodPers( java.lang.String cod_pers ) ;

   public void setOperacion( java.lang.String operacion ) ;

   public void setFGraba( java.sql.Timestamp fgraba ) ;

   public void setCUser( java.lang.String cuser ) ;

   public java.lang.String getUOrgan(  ) ;

   public java.lang.String getCodPers(  ) ;

   public java.lang.String getOperacion(  ) ;

   public java.sql.Timestamp getFGraba(  ) ;

   public java.lang.String getCUser(  ) ;

}
