/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Local interface for T45CMP.
 * @xdoclet-generated at 03-02-2020
 */
public interface T45CMPLocal
   extends javax.ejb.EJBLocalObject
{

   public void setCodTurno( java.lang.String codTurno ) ;

   public void setDesTurno( java.lang.String desTurno ) ;

   public void setFInicio( java.lang.String fInicio ) ;

   public void setHInicio( java.lang.String hInicio ) ;

   public void setFFfin( java.lang.String fFfin ) ;

   public void setHFin( java.lang.String hFin ) ;

   public void setEstId( java.lang.String estId ) ;

   public void setDiasInt( java.lang.String diasInt ) ;

   public void setTolera( java.lang.String tolera ) ;

   public void setHLimit( java.lang.String hLimit ) ;

   public void setOperId( java.lang.String operId ) ;

   public void setControlId( java.lang.String controlId ) ;

   public void setFGraba( java.sql.Timestamp fGraba ) ;

   public void setRefrIni( java.lang.String refrIni ) ;

   public void setRefrFin( java.lang.String refrFin ) ;

   public void setRefrMin( java.lang.String refrMin ) ;

   public void setCuser( java.lang.String cuser ) ;

   public java.lang.String getCodTurno(  ) ;

   public java.lang.String getDesTurno(  ) ;

   public java.lang.String getFInicio(  ) ;

   public java.lang.String getHInicio(  ) ;

   public java.lang.String getFFfin(  ) ;

   public java.lang.String getHFin(  ) ;

   public java.lang.String getEstId(  ) ;

   public java.lang.String getDiasInt(  ) ;

   public java.lang.String getTolera(  ) ;

   public java.lang.String getHLimit(  ) ;

   public java.lang.String getOperId(  ) ;

   public java.lang.String getControlId(  ) ;

   public java.sql.Timestamp getFGraba(  ) ;

   public java.lang.String getRefrIni(  ) ;

   public java.lang.String getRefrFin(  ) ;

   public java.lang.String getRefrMin(  ) ;

   public java.lang.String getCuser(  ) ;

}
