/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Remote interface for TurnoTrabajoFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface TurnoTrabajoFacadeRemote
   extends javax.ejb.EJBObject
{

   public java.util.ArrayList buscarTurnosTrabajo( java.lang.String dbpool,java.lang.String criterio,java.lang.String valor )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   public java.util.ArrayList eliminarTurnosTrabajo( java.lang.String[] params,java.util.ArrayList lista )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   public java.lang.String modificarTurnoTrabajo( java.util.Map mapa )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   public pe.gob.sunat.sp.asistencia.bean.BeanTurnoTrabajo buscarTrabTurno( java.lang.String dbpool,java.lang.String codPers,java.lang.String fecha )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   public void procesarOperativo( java.lang.String dbpool,java.util.ArrayList trabajadores,java.util.ArrayList detalle,java.lang.String fechaIni,java.lang.String fechaFin,boolean bSabado,boolean bDomingo,boolean bFeriado,java.lang.String codPersUsuario,java.lang.String usuario )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   public java.util.ArrayList buscarTurnosTrabajo( java.lang.String dbpool,java.lang.String fechaIni,java.lang.String fechaFin,java.lang.String codTurno,java.lang.String criterio,java.lang.String valor,java.util.HashMap seguridad )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   public void registrarTurnoTrabajo( java.util.HashMap mapa,java.lang.String usuario )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   public void registrarTurnoCompensa( java.util.HashMap datos )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   public int calcularHorasCompensa( java.lang.String dbpool,java.lang.String codPers,java.lang.String fechaIni,java.lang.String fechaFin )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   /**
    * AJUSTES A 8 HORAS DE RECUPERACION PARA DL 1057(CAS) Y DL 276-728 POR CADA DIA DE FERIADO COMPENSABLE
    */
   public int calcularHorasCompensaModif( java.lang.String dbpool,java.lang.String codPers,java.lang.String fechaIni,java.lang.String fechaFin )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

   /**
    * Metodo encargado de la Planificacion de Turnos Masivos
    * @param dbean DynaBean
    * @throws IncompleteConversationalState
    * @throws RemoteException    */
   public void planificarTurnosMasivos( pe.gob.sunat.framework.core.pattern.DynaBean dbean )
      throws pe.gob.sunat.sol.IncompleteConversationalState, java.rmi.RemoteException;

}
