/*
 * Generated by XDoclet - Do not edit!
 */
package pe.gob.sunat.sp.asistencia.ejb;

/**
 * Home interface for TurnoTrabajoFacadeEJB.
 * @xdoclet-generado el 03-02-2020
 */
public interface TurnoTrabajoFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TurnoTrabajoFacadeEJB";
   public static final String JNDI_NAME="ejb/rrhh/facade/sp/asistencia/TurnoTrabajoFacadeEJB";

   public pe.gob.sunat.sp.asistencia.ejb.TurnoTrabajoFacadeRemote create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
